# k8s/base/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: yb-api-service
  namespace: yellowbooks
  labels:
    app: yb-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
    name: http
  selector:
    app: yb-api