# k8s/base/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: yb-web-service
  namespace: yellowbooks
  labels:
    app: yb-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: yb-web